### Create Author
POST {{base_url}}/authors
Content-Type: application/json
Authorization: {{auth}}

{
  "name": "Adam",
  "lastName": "Mickiewicz",
  "bio": "Polish poet, dramatist, essayist, publicist, translator and political activist."
}

> {% client.global.set("author_id", response.body.id); %}

### List Authors (public)
GET {{base_url}}/authors

### Get Author (public)
GET {{base_url}}/authors/{{author_id}}

### Get Author Manual (public)
GET {{base_url}}/authors/1

### Full Update Author
PUT {{base_url}}/authors/{{author_id}}
Content-Type: application/json
Authorization: {{auth}}

{
  "name": "Adam Bernard",
  "lastName": "Mickiewicz",
  "bio": "Updated bio: Polish poet and dramatist."
}

### Partial Update Author
PATCH {{base_url}}/authors/{{author_id}}
Content-Type: application/json
Authorization: {{auth}}

{
  "bio": "Partially updated bio."
}

### Delete Author
DELETE {{base_url}}/authors/{{author_id}}
Authorization: {{auth}}
