### Create Genre
POST {{base_url}}/genres
Content-Type: application/json
Authorization: {{auth}}

{
  "name": "Epic Poetry"
}

> {% client.global.set("genre_id", response.body.id); %}

### List Genres (public)
GET {{base_url}}/genres

### Get Genre (public)
GET {{base_url}}/genres/{{genre_id}}

### Delete Genre
DELETE {{base_url}}/genres/{{genre_id}}
Authorization: {{auth}}
