### Create Genre
POST {{base_url}}/genres
Content-Type: application/json

{
  "name": "Epic Poetry"
}

> {% client.global.set("genre_id", response.body.id); %}

### List Genres
GET {{base_url}}/genres

### Get Genre
GET {{base_url}}/genres/{{genre_id}}

### Delete Genre
DELETE {{base_url}}/genres/{{genre_id}}
