### Create Reservation
POST {{base_url}}/reservations
Content-Type: application/json
Authorization: {{auth}}

{
  "user": { "id": 1 },
  "book": { "id": 1 },
  "status": "OCZEKUJĄCA"
}

> {% client.global.set("reservation_id", response.body.id); %}

### List Reservations
GET {{base_url}}/reservations
Authorization: {{auth}}

### Get Reservation
GET {{base_url}}/reservations/{{reservation_id}}
Authorization: {{auth}}

### Partial Update Reservation
PATCH {{base_url}}/reservations/{{reservation_id}}
Content-Type: application/json
Authorization: {{auth}}

{
  "status": "POTWIERDZONA"
}

### Delete Reservation
DELETE {{base_url}}/reservations/{{reservation_id}}
Authorization: {{auth}}
